# Generated by Django 5.1.6 on 2025-02-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donkey_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
    ]
